Fixed incorrect file permissions on `/opt/nautobot/nautobot_config.py` in `final` Docker images.
